### ISSUE TITLE
Schaefer Updates

### ISSUE THREAD

**Issue by l-espana** [HALFpipe/Atlases#1]
Thanks for providing these atlases! 
I just want to confirm that the Schaefer atlases do **not** use the updated labels from 2019? They haven't updated in templateflow yet, which may be part of the issue as well. 
Links for reference:
https://github.com/ThomasYeoLab/CBIG/tree/v0.14.3-Update_Yeo2011_Schaefer2018_labelname/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/Updates
https://github.com/templateflow/templateflow/issues/119

**Comment by HippocampusGirl** [comment]
Hi Lezlie,
I did not know about the updated labels, thank you for bringing this to my attention! I will make sure the labels are in the next release
